import type { Metadata } from "next";
import "./globals.css";
import { Header } from "../components/layouts/header";
import { Footer } from "../components/layouts/footer";
import { Provider } from "react-redux";
import { store } from "../store/redux.store";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}
